name: Build

on: push

jobs:
  SyncTag:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x # Run with latest stable Deno.
      
      - name: Bump Tag
        run: deno task cache

      - name: Bump Tag
        run: deno task bump-tag
